server:
  port: 9001
spring:
  application:
    name: jblog-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.1:3306/
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
