server:
  port: 9014
spring:
  application:
    name: blog-spider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.dongpl.com:3306/jblog?characterEncoding=UTF-8
    username: jblog
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 127.0.0.1
